### ISSUE TITLE
Drag over functionality

### ISSUE THREAD

**Issue by kaushal4340** [Kuniwak/html-dnd#14]
Hello Authors,

Do we have drag over functionality with functional tests in nightwatch?

How to do it in html-dnd ?

**Comment by Kuniwak** [comment]
Unfortunately, this feature is not implemented yet.
I don't have time for this feature, but I can review if you send a Pull request for this feature.

**Comment by adrienverge** [comment]
@PloughingAByteField implemented this: https://github.com/PloughingAByteField/html-dnd/commits/56f76a6

It is a very useful feature indeed, as some programs need `dragover` events to work correctly.

@Kuniwak Should I make a PR for this (using @PloughingAByteField's commits)?

**Comment by PloughingAByteField** [comment]
Are you going to add in the offset support or just the dragover?

**Comment by adrienverge** [comment]
I was thinking about the dragover, but I can add the offset support if you and @Kuniwak think it's better.

**Comment by PloughingAByteField** [comment]
I added the offset to support the dnd library I was using, there, as away's, pros and cons about using such a mechanism. 
It was added to allow the drop to be placed before the item being dropped upon (particularly if there is only one item in the drop area), this may or may not be a feature you want to support as some dnd libraries do funky stuff
I add a choice comment from angular-drag-and-drop-lists v1.4.0

 // If the mouse pointer is in the upper half of the child element,
 // we place it before the child element, otherwise below it.

**Comment by adrienverge** [comment]
In this case it's better to make a pull request with dragover support only. I'll do it as soon as we have feedback from the original author.

**Comment by kaushal4340** [comment]
can you please add code sample how to use dragover with nightwatch ?

**Comment by Kuniwak** [comment]
@adrienverge Sorry for my too late reply ... :bowing_man: 

I welcome to the PR!
I can review it if you send the PR.

Thanks.
