### ISSUE TITLE
html-dnd does not seem to work with Node 12.2.0

### ISSUE THREAD

**Issue by cskubatz** [Kuniwak/html-dnd#30]
I use nightwatch to run e2e tests. To get drag and drop test cases working i am using html-dnd since a year. Now i **updated my node.js version from 10.10.0 to 12.2.0 (current)** and the drag and drop test cases arent working anymore. I get this console output:

`Running:  Copying page node and checking if content text options have been preserved
   {"sessionId":"179791e903830106402876e488ca1f38","status":0,"value":[],"abortOnFailure":true}
       at processTicksAndRejections (internal/process/task_queues.js:89:5)
FAILED: 1 errors (420ms)`

I saw this error from time to time but the reason was that one of the selectors (drag, drop) was wrong or not reachable. When i fixed the selector the test case was running smoothly after it.

Now i **got this error on every drag and drop command**, also in test cases that were running for months correctly.

"chromedriver": "74.0.0",
"html-dnd": "1.2.0",
"nightwatch": "1.0.6"

Has someone experienced the same problem? Every hint will be appreciated.

Thanks,
Chris

**Comment by devoto13** [comment]
I think we faced same issue. The problem is that in Node 12 dnd code is not correctly formatted. If you log dnd code using something like:

```
var dragAndDrop = require('html-dnd').code;
console.log(dragAndDrop);
```

You'll probably see `<Buffer ...>` in the output. If this is the case you can workaround it by reading file with code and formatting it yourself instead of importing from the library.

Relevant code: https://github.com/html-dnd/html-dnd/blob/master/lib/index.js#L8-L15
Note that you'll need to do `var coreCode = fs.readFileSync(CODE_FILE, {encoding: 'utf8'});` to read the dnd code as a string instead of bytes.

**Comment by cskubatz** [comment]
Thank you for the clarification. I will try this as soon as possible. It would be nice if this will be included in the package. But it seems that the maintenance of the package has been stagnating or discontinued for years. In any case, thanks for your effort - i appreciate that.
